### PR TITLE
Explanation

### PR DESCRIPTION
**Pull request by kargakis**

### CODE REVIEW

**Comment by kargakis** [comment]
The branch already exists so subsequent comments will fail
```
{"client":"github","level":"debug","msg":"GetPullRequest(kargakis, test, 4)","time":"2017-10-16T15:40:09Z"}
{"client":"git","level":"info","msg":"Fetching kargakis/test.","time":"2017-10-16T15:40:09Z"}
{"client":"git","level":"info","msg":"Checkout stage.","time":"2017-10-16T15:40:10Z"}
{"client":"cherrypicker","duration":318919307,"level":"info","msg":"Cloned and checked out target branch.","time":"2017-10-16T15:40:10Z"}
{"client":"git","level":"info","msg":"Running git config user.name cherrypicker","time":"2017-10-16T15:40:10Z"}
{"client":"git","level":"info","msg":"Running git config user.email cherrypicker@localhost","time":"2017-10-16T15:40:10Z"}
{"client":"git","level":"info","msg":"Applying /tmp/4-4b45f2ca-b288-11e7-959c-0a58ac10120e.patch.","time":"2017-10-16T15:40:10Z"}
{"client":"git","level":"info","msg":"Create and checkout cherry-pick-4-to-stage.","time":"2017-10-16T15:40:10Z"}
{"client":"git","level":"info","msg":"Pushing to 'kargakis-bot/test cherry-pick-4-to-stage'.","time":"2017-10-16T15:40:10Z"}
{"client":"cherrypicker","error":"exit status 1","level":"info","msg":"Cherry-pick failed.","time":"2017-10-16T15:40:10Z"}
```
I could maybe bubble that error in a comment.

**Comment by xiangpengzhao** [comment]
So do we also want to clean up the branch and other stale stuff when merged or when some steps fail?

**Comment by xiangpengzhao** [comment]
`Base branch (master) needs to be 'master' and differ from target branch (master)` this is a bit confusing to me at this context. I'd like to see something like `Target branch (master) shouldn`t be 'master' and differ from base branch (master)`

**Comment by kargakis** [comment]
> So do we also want to clean up the branch and other stale stuff when merged or when some steps fail?

The only thing that gets stale is the branch once it's pushed in the fork and gets merged upstream. We can clean it up but it's not necessary.

**Comment by kargakis** [comment]
> Base branch (master) needs to be 'master' and differ from target branch (master) this is a bit confusing to me at this context. I'd like to see something like Target branch (master) shouldnt be 'master' and differ from base branch (master)`

Yeah, that message can use some polishing.

**Pull request merged**
